### ISSUE TITLE
fail to exstract pmml

### ISSUE THREAD

**Issue by moseshu** [vaclavcadek/keras2pmml#11]
I still have the issues, when exstract keras Model to pmml file,it gave me the error like this?
how to solve this Issue?
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras2pmml/__init__.py", line 146, in <lambda> 
 
layer_activations = map(lambda x: x['config']['activation'], estimator.get_config())
TypeError: string indices must be integers

**Comment by vaclavcadek** [comment]
This is a duplicate of https://github.com/vaclavcadek/keras2pmml/issues/10

Please, don't recreate issues just to emphasise them.
